In [1]:
import numpy as np

In [2]:
lista = [1, 2, 3, 4, 5, 6]

array = np.array(lista)

In [4]:
print(type(lista))
print(type(array))

<class 'list'>
<class 'numpy.ndarray'>


In [5]:
arr_zeros = np.zeros(10)

print(arr_zeros)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [6]:
array[0] = 9
print(array)

[9 2 3 4 5 6]


In [9]:
## matrizes
matriz_zeros = np.zeros((5, 3))
print(matriz_zeros)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [10]:
## Notas de alunos
lista_de_notas = [9.8, 5.6, 7.8, 9.1, 6.5]
notas = np.array(lista_de_notas)

In [11]:
print('Maximo', notas.max())
print('Mínimo', notas.min())
print('Desvio Padrao', notas.mean())
print('Posicao menor', notas.argmin())

Maximo 9.8
Mínimo 5.6
Desvio Padrao 7.76
Posicao menor 1
